language: clojure

clojure:
  - 1.10.0-RC4

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
  - chmod +x linux-install-1.10.0.411.sh
  - sudo ./linux-install-1.10.0.411.sh
  - sudo apt-get install rlwrap wget unzip
  - wget https://github.com/candid82/joker/releases/download/v0.11.0/joker-0.11.0-linux-amd64.zip
  - unzip joker-0.11.0-linux-amd64.zip
  - sudo mv joker /usr/bin/
  - find ./src -type f -exec joker --lint {} \;



script:
  - make test
  - make lint
