language: clojure

clojure:
  - 1.10.0-RC4

install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
  - chmod +x linux-install-1.10.0.411.sh
  - sudo ./linux-install-1.10.0.411.sh
  - sudo apt-get install rlwrap

script:
  - make lint
  - make test
