# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.0.408-node-browsers-legacy
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
    
    steps:
      - checkout
      - run: curl -O https://download.clojure.org/install/linux-install-1.10.0.411.sh
      - run: chmod +x linux-install-1.10.0.411.sh
      - run: sudo ./linux-install-1.10.0.411.sh
      - run: sudo apt-get install build-essential wget unzip
      - run: wget https://github.com/candid82/joker/releases/download/v0.11.0/joker-0.11.0-linux-amd64.zip
      - run: unzip joker-0.11.0-linux-amd64.zip
      - run: sudo mv joker /usr/bin/

      # run tests!
      - run: make lint
      - run: make format
      - run: make test
